name: tensegrity
channels:
  - conda-forge
  - defaults
dependencies:
  - ffmpeg=4.3.2
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - numpy=1.21.5
  - packaging=21.3
  - pandas=1.4.2
  - python=3.8.13
  - scipy=1.9.1
  - seaborn=0.11.2
  - setuptools=65.5.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0

